# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:  
  pwa:
    container_name: pwa
    build:
      context: .
      dockerfile: Dockerfile-node.prod
    ports:
      - '1337:80'
  api:
    image: api
    build: .
    command: gunicorn --reload -b 0.0.0.0:5555 api.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DEBUG=false
      - FLASK_ENV=prod
      - DATABASE_URI=mongodb://host.docker.internal:27017/gene_discovery
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULT_BACKEND_URL=redis://redis
    volumes:
      - ./api:/code/api
      # - ./db/:/db/
    ports:
      - "5555:5555"
  rabbitmq:
    image: rabbitmq
  redis:
    image: redis
  celery:
    image: api
    build: .
    command: "celery worker -A api.celery_app:app"
    env_file:
      - ./.flaskenv
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULT_BACKEND_URL=redis://redis
