# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:  
  nodejs:
    container_name: gpad_pwa
    build:
      context: .
      dockerfile: Dockerfile-node
    env_file:
      - .env
    volumes:
      - './pwa:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  api:
    container_name: gpad_api
    image: api
    build: .
    command: gunicorn --reload -b 0.0.0.0:5555 api.wsgi:app
    env_file:
      - .env
    volumes:
      - ./Makefile:/code/Makefile
      - ./api:/code/api
      - ./data:/code/data
      - ./logs:/code/logs
    ports:
      - "5555:5555"
      - "5000:5000"

  mongo:
    image: mongo:5.0
    container_name: gpad_mongo
    restart: always
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./db:/data/db
    ports:
      - "27019:27017"

  # PowerBI integration service
  # mongobi:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-mongobi
  #   environment:
  #     MONGODB_HOST: host.docker.internal
  #     MONGODB_PORT: 27019
  #   ports:
  #     - 3307:3307