FROM node:13.12.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./pwa/package.json ./
COPY ./pwa/package-lock.json ./
RUN npm ci
RUN npm install react-scripts@3.4.1 -g
COPY ./pwa ./
RUN npm run build
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]