# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:  
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile-node
    env_file:
      - .env
    volumes:
      - './pwa:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    image: api
    build: .
    command: gunicorn --reload -b 0.0.0.0:5555 api.wsgi:app
    env_file:
      - .env
    volumes:
      - ./api:/code/api
      - ./data:/code/data
      - ./logs:/code/logs
    ports:
      - "5555:5555"  
  db:
    image: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - ./db:/data/db
    ports:
      - "27018:27017"  
  rabbitmq:
    image: rabbitmq
  redis:
    image: redis
  celery:
    image: api
    build: .
    command: "celery worker -A api.celery_app:app"
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULT_BACKEND_URL=redis://redis
