
# from .data_curation import *
from api.gene_discovery.data_curation import Curator, nearest_publication_detector
from .models import *

def test_nearest_publication():
    test_text = [
        (60, "{1:Fischer-Zirnsak et al. (2019)} reported 14 patients from 11 unrelated families with a similar neurodevelopmental disorder. The patients were ascertained through international collaborative research efforts and GeneMatcher. Most were children, although 1 was 16 and another was 35; an affected mother was also reported (without an exact age). All individuals had some sort of developmental delay with impaired intellectual development, often accompanied by autism spectrum disorder, autistic features, attention deficit, stereotypic behavior, and/or structural brain abnormalities on imaging. Clinical details of many patients were limited, but some had speech delay, patient 6 had an IQ of 55, patient 10 had an IQ of 91, and a few were able to attend school. Five patients had seizures. All 11 patients who underwent brain imaging showed nonspecific and variable abnormalities, including hydrocephalus, ventriculomegaly, thin, short, or dysplastic corpus callosum, subtle cortical dysplasia, and small cerebellum or pons. One patient had periventricular nodular heterotopia. Dysmorphic features were noted in many patients, mainly upslanting palpebral fissures, although there was not a consistent recognizable phenotype. Additional common features included hypotonia, hyperextensible joints, ataxia, and kyphosis/scoliosis. Less common features included neonatal hyperbilirubinemia, sacral dimple, syringomyelia, and eye movement abnormalities."),
        (65, "{1:Armfield et al. (1999)} reported a family with 6 males with mental retardation in 3 generations, consistent with X-linked inheritance. Other features included short stature (6 of 6), small hands and feet (5 of 5), seizures (6 of 6), cleft palate (2 of 6), and cataracts/glaucoma (3 of 6). Carrier females were unaffected. {2:Lee et al. (2020)} provided follow-up of 2 of the affected males in the family reported by {1:Armfield et al. (1999)}. They were 28 and 24 years of age and had lifelong cognitive impairment requiring special schooling. Both had short stature and large head circumference, as well as dysmorphic features, including prominent forehead, downslanting palpebral fissures, epicanthal folds, depressed nasal bridge, micrognathia, short philtrum, crowded teeth, narrow palate, myopia, small hands and feet, hammertoes, and limited joint mobility. Both had seizures. IQ in 1 patient was 66. Brain imaging showed enlarged or asymmetric ventricles.\n\n{2:Lee et al. (2020)} reported 4 unrelated male patients, ranging in age from 10 to 26 years, with MRXSA. The patients were found through the GeneMatcher program; none had a family history of a similar disorder. All had global developmental delay, but the severity was variable. Two patients (K9648 and K9667) had no speech and walking difficulties requiring a walker or wheelchair. One had a feeding tube and the other had an IQ less than 50. The other 2 patients (K9656 and K9677) had mildly impaired intellectual development with ability to speak and ambulate; 1 lived in a group home and had an IQ of 63. One patient developed seizures at age 9 years. All had variable dysmorphic facial features with some overlap, including prominent forehead, bitemporal narrowing, exotropia, hypotelorism, epicanthus, myopia, keratoconus, wide nasal root, short nose, bulbous nose, prominent lips, micrognathia, hypodontia, hemangiomas, excessively folded ear helices, and small hands and feet. Additional features observed in some patients included short stature, kyphoscoliosis, clubfoot, cryptorchidism, micropenis, small scrotum, hiatal or inguinal hernia, hypotonia, hypertonia, dysphagia, large head circumference, and nystagmus. Each patient had involvement of other systems, including imperforate anus (1), sacral dimple with tethered cord (1), tetralogy of Fallot (1), horseshoe kidney (1), Axenfeld-Rieger anomaly with glaucoma (1), renal agenesis (1), atrial septal defect (1), and 2-vessel cord (1). Brain imaging, performed in 1 patient, showed decreased white matter, small corpus callosum, and small brainstem."),
        (200, "{1:Armfield et al. (1999)} reported a family with 6 males with mental retardation in 3 generations, consistent with X-linked inheritance. Other features included short stature (6 of 6), small hands and feet (5 of 5), seizures (6 of 6), cleft palate (2 of 6), and cataracts/glaucoma (3 of 6). Carrier females were unaffected. {2:Lee et al. (2020)} provided follow-up of 2 of the affected males in the family reported by {1:Armfield et al. (1999)}. They were 28 and 24 years of age and had lifelong cognitive impairment requiring special schooling. Both had short stature and large head circumference, as well as dysmorphic features, including prominent forehead, downslanting palpebral fissures, epicanthal folds, depressed nasal bridge, micrognathia, short philtrum, crowded teeth, narrow palate, myopia, small hands and feet, hammertoes, and limited joint mobility. Both had seizures. IQ in 1 patient was 66. Brain imaging showed enlarged or asymmetric ventricles.\n\n{2:Lee et al. (2020)} reported 4 unrelated male patients, ranging in age from 10 to 26 years, with MRXSA. The patients were found through the GeneMatcher program; none had a family history of a similar disorder. All had global developmental delay, but the severity was variable. Two patients (K9648 and K9667) had no speech and walking difficulties requiring a walker or wheelchair. One had a feeding tube and the other had an IQ less than 50. The other 2 patients (K9656 and K9677) had mildly impaired intellectual development with ability to speak and ambulate; 1 lived in a group home and had an IQ of 63. One patient developed seizures at age 9 years. All had variable dysmorphic facial features with some overlap, including prominent forehead, bitemporal narrowing, exotropia, hypotelorism, epicanthus, myopia, keratoconus, wide nasal root, short nose, bulbous nose, prominent lips, micrognathia, hypodontia, hemangiomas, excessively folded ear helices, and small hands and feet. Additional features observed in some patients included short stature, kyphoscoliosis, clubfoot, cryptorchidism, micropenis, small scrotum, hiatal or inguinal hernia, hypotonia, hypertonia, dysphagia, large head circumference, and nystagmus. Each patient had involvement of other systems, including imperforate anus (1), sacral dimple with tethered cord (1), tetralogy of Fallot (1), horseshoe kidney (1), Axenfeld-Rieger anomaly with glaucoma (1), renal agenesis (1), atrial septal defect (1), and 2-vessel cord (1). Brain imaging, performed in 1 patient, showed decreased white matter, small corpus callosum, and small brainstem."),
        # (450, "In affected males from 5 unrelated families with MRXSA, {2:Lee et al. (2020)} identified heterozygous missense mutations in the FAM50A gene ({300453.0001}-{300453.0005}). The mutation in the first family, which was the original family reported by {1:Armfield et al. (1999)}, was found by Sanger sequencing of candidate genes within the linked interval. Four additional unrelated males with the disorder were subsequently identified through the GeneMatcher database. Three of the mutations from the unrelated patients occurred de novo, and 1 was inherited from an unaffected mother. All mutations were missense variants that occurred at highly conserved residues in the XAP domain, and none were present in the gnomAD database. RNA analysis of peripheral blood cells from 2 patients showed evidence for dysregulation of the transcriptome and a spliceosomal defect. None of the mutants were able to fully rescue the phenotypic defects in fam50a-null zebrafish, suggesting that the alleles are hypomorphic."),
        # (60, "In affected males from 5 unrelated families with MRXSA, {2:Lee et al. (2020)} identified heterozygous missense mutations in the FAM50A gene ({300453.0001}-{300453.0005}). The mutation in the first family, which was the original family reported by {1:Armfield et al. (1999)}, was found by Sanger sequencing of candidate genes within the linked interval. Four additional unrelated males with the disorder were subsequently identified through the GeneMatcher database. Three of the mutations from the unrelated patients occurred de novo, and 1 was inherited from an unaffected mother. All mutations were missense variants that occurred at highly conserved residues in the XAP domain, and none were present in the gnomAD database. RNA analysis of peripheral blood cells from 2 patients showed evidence for dysregulation of the transcriptome and a spliceosomal defect. None of the mutants were able to fully rescue the phenotypic defects in fam50a-null zebrafish, suggesting that the alleles are hypomorphic."),
        (15, "In 1 of the original Japanese patients with glycogen storage disease type VII (GSD7; {232800}) reported by {16:Tarui et al. (1965)}, {9:Nakajima et al. (1990)} identified a G-to-T transversion at the 5-prime end of intron 13 of the PFKM gene, resulting in a splice site mutation and a 75-bp (25-residue) in-frame deletion in the 3-prime portion of exon 13. A cryptic splice site located 75 bases upstream from the normal splice site was identified. The mutation was predicted to result in drastic configurational changes in the protein, leading to loss of catalytic activity. Since the parents were consanguineous, {9:Nakajima et al. (1990)} assumed that the mutation was homozygous. {8:Nakajima (1997)} noted that at the original publication of this mutation in 1990, only the rabbit gene was sequenced; therefore, the exon numbering followed that of rabbit Pfkm. Later studies by {23:Yamasaki et al. (1991)} determined the full genomic structure of the gene and showed that intron 15 is the appropriate numbering for this mutation.")
    ]
    assert_check = [
        ("1", "Fischer-Zirnsak et al", "2019"),
        ("1", "Armfield et al", "1999"),
        ("1", "Armfield et al", "1999"),
        # ("1", "Armfield et al", "1999"),
        # ("2", "Lee et al", "2020"),
        # ("24", "Yoo et al", "2016"),
        ("9", "Nakajima et al", "1990"),
    ]
    for idx, text in enumerate(test_text):
        print(idx)
        nearest_match = nearest_publication_detector(text[1], text[0])
        assert nearest_match.group(1) == assert_check[idx][0]
        assert nearest_match.group(2) == assert_check[idx][1]
        assert nearest_match.group(3) == assert_check[idx][2]

def test_nearest_publication_detector():
    mims_to_check = [168601]
        
    curation = Curator()
    curation.curate(mims_to_check)


# def test_earliest_evidence_view():
#     processed_evidences = EarliestPhenotypeEvidences.objects.only('gene_mim_id')
#     print(len(processed_evidences))
#     assert len(processed_evidences) > 0